Replace 'qvm-template purge' with 2-step qvm-remove
A bug (qubes-issues#10879) was preventing successful purge of all Whonix
qubes:

   $ qvm-template purge whonix-gateway-17 whonix-workstation-17
   [...]
   Property 'default_dispvm' of 'anon-whonix' set to 'dummy'.
   ERROR: The dummy qube does not provide network

A temporary workaround is to remove in two stages. First the derived
qubes (whose interdependencies qvm-remove seems to be able to handle)
and then a second qvm-remove for the templates.

NOTE: unlike 'qvm-template purge', 'qvm-remove' is order-dependent. So
we must specify qvm-remove for the least dependent qubes first.
(Hopefully there are no cycles).