Fix updater failure on updating templates
The updater was failing with the following error message:

>    File "/usr/lib/python3.11/site-packages/sdw_updater/Updater.py", line 192, in _qubes_updater_parse_stdout
>      line = Util.cleanup_for_log(line.decode("ascii")).rstrip()
>                                ^^^^^^^^^^^
>  AttributeError: 'str' object has no attribute 'decode'. Did you mean: 'encode'?

This was introduced in the recent 1.5.2 release.

Fixes #1618